apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfamily-app
  labels:
    app: myfamily
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myfamily
  template:
    metadata:
      labels:
        app: myfamily
    spec:
      containers:
        - name: myfamily-container
          image: docker.io/saikumarbandike/myfamily:latest
          ports:
            - containerPort: 80
