apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsNCiAgICAgICJ1c2VybmFtZSI6ICJzYWlrdW1hcmJhbmRpa2UiLA0KICAgICAgInBhc3N3b3JkIjogImRja3JfcGF0X24zbi03ZEZBY1NiSTZmMXphUWUxdzVhT0hvNCIsDQogICAgICAiZW1haWwiOiAieW91QGV4YW1wbGUuY29tIiwNCiAgICAgICJhdXRoIjogIkJBU0U2NChjMkZwYTNWdFlYSmlZVzVrYVd0bE9tUmphM0pmY0dGMFgyNHpiaTAzWkVaQlkxTmlTVFptTVhwaFVXVXhkelZoVDBodk5BPT0pIg0KICAgIH0NCiAgfQ0KfQ0K
